files/usr/share/grase/symfony4/src/Entity/Radius/User.php
<?php

namespace App\Entity\Radius;

use App\Util\DateIntervalEnhanced;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\Entity\Radius\UserRepository")
 */
class User
{
    public const RADIUS_CONFIG_USER = 'CoovaChilli';
    /**
     * @ORM\Column(type="string", length=64)
     * @ORM\Id
     *
     * @Groups({"user_get"})
     */
    private $username;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Groups({"user_get"})
     */
    private $comment;

    /**
     * @ORM\OneToMany(targetEntity="Check", mappedBy="user", fetch="EAGER")
     *
     * @var Check[]
     */
    private $radiusCheck;

    /**
     * @ORM\OneToMany(targetEntity="Reply", mappedBy="user", fetch="EAGER")
     *
     * @var Reply[]
     */
    private $radiusReply;

    /**
     * @ORM\OneToMany(targetEntity="UserGroup", mappedBy="user", fetch="EAGER", cascade={"persist", "remove"})
     *
     * @Groups({"user_get"})
     */
    private $userGroups;

    /**
     * @ORM\OneToMany(targetEntity="Radacct", mappedBy="user", fetch="LAZY")
     */
    private $radiusAccounting;

    /**
     * Private variables for internal use
     */
    /** @var DateIntervalEnhanced */
    private $currentSessionTime = null;
    private $currentDataUsage = null;
    private $currentDataUsageIn = null;
    private $currentDataUsageOut = null;
    /** @var DateTime */
    private $lastLogout = null;

    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->radiusCheck = new ArrayCollection();
        $this->radiusReply = new ArrayCollection();
        $this->userGroups = new ArrayCollection();
        $this->radiusAccounting = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @Groups({"user_get"})
     *
     * @return string|null
     */
    public function getPassword()
    {
        if ($this->getPasswordCheck()) {
            return $this->getPasswordCheck()->getValue();
        }

        return null;
    }

    /**
     * @return Check
     */
    public function getPasswordCheck()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('attribute', 'Cleartext-Password'));

        return $this->getRadiuscheck()->matching($criteria)->first();
    }

    /**
     * Get the users time limit in a somewhat formatted way (good for displaying)
     *
     * @Groups({"user_get"})
     *
     * @return string
     */
    public function getTimeLimit()
    {
        if ($this->getTimeLimitCheck()) {
            $timeLimit = new DateIntervalEnhanced('PT' . $this->getTimeLimitCheck()->getValue() . 'S');

            return $timeLimit->recalculate()->format('%H:%I:%S');
        }

        return '∞';
    }

    /**
     * @return Check
     */
    public function getTimeLimitCheck()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('attribute', 'Max-All-Session'));

        return $this->getRadiuscheck()->matching($criteria)->first();
    }

    /**
     * Get the users time limit in Minutes, needed for editing users
     *
     * @return float|int
     */
    public function getTimeLimitMinutes()
    {
        return $this->getTimeLimitSeconds() / 60;
    }

    /**
     * Get the users Time limit as seconds or null if there is no limit
     *
     * @return string|null
     */
    public function getTimeLimitSeconds()
    {
        if ($this->getTimeLimitCheck()) {
            return $this->getTimeLimitCheck()->getValue();
        }

        return null;
    }

    /**
     * Get the users data limit as a mebibyte value, needed when editing users
     *
     * @return float|int|null
     */
    public function getDataLimitMebibyte()
    {
        return null !== $this->getDataLimit() ? $this->getDataLimit() / 1024 / 1024 : null;
    }

    /**
     * Get the users Data limit as it's raw bytes value
     *
     * @Groups({"user_get"})
     *
     * @return string | null
     */
    public function getDataLimit()
    {
        if ($this->getDataLimitCheck()) {
            return $this->getDataLimitCheck()->getValue();
        }

        return null;
    }

    /**
     * @return Check
     */
    public function getDataLimitCheck()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('attribute', 'Max-Octets'));

        return $this->getRadiuscheck()->matching($criteria)->first();
    }

    /**
     * @Groups({"user_get"})
     *
     * @return DateTime|null
     */
    public function getExpiry()
    {
        if ($this->getExpiryCheck()) {
            return new \DateTime($this->getExpiryCheck()->getValue());
        }

        return null;
    }

    /**
     * @return Check
     */
    public function getExpiryCheck()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('attribute', 'Expiration'));

        return $this->getRadiuscheck()->matching($criteria)->first();
    }

    /**
     * @return Check
     */
    public function getExpireAfterCheck()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('attribute', Check::GRASE_EXPIRE_AFTER));

        return $this->getRadiuscheck()->matching($criteria)->first();
    }

    /**
     * @return string|null
     */
    public function getExpireAfter()
    {
        if ($this->getExpireAfterCheck()) {
            return $this->getExpireAfterCheck()->getValue();
        }

        return null;
    }

    /**
     * Add radiuscheck
     *
     * @param Check $radiuscheck
     *
     * @return User
     */
    public function addRadiuscheck(Check $radiuscheck)
    {
        $this->radiusCheck[] = $radiuscheck;

        return $this;
    }

    /**
     * Remove radiuscheck
     *
     * @param Check $radiuscheck
     */
    public function removeRadiuscheck(Check $radiuscheck)
    {
        $this->radiusCheck->removeElement($radiuscheck);
    }

    /**
     * Get all the Radius Check Entries
     *
     * @return Check[]
     */
    public function getRadiuscheck()
    {
        return $this->radiusCheck;
    }

    /**
     * Add radius reply
     *
     * @param Reply $radiusReply
     *
     * @return User
     */
    public function addRadiusReply(Reply $radiusReply)
    {
        $this->radiusReply[] = $radiusReply;

        return $this;
    }

    /**
     * Remove radius reply
     *
     * @param Reply $radiusReply
     */
    public function removeRadiusReply(Reply $radiusReply)
    {
        $this->radiusReply->removeElement($radiusReply);
    }

    /**
     * Get all the Radius Reply Entries
     *
     * @return Reply[]
     */
    public function getRadiusReply()
    {
        return $this->radiusReply;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    }

    /**
     * Add userGroups
     *
     * @param UserGroup $userGroups
     *
     * @return User
     */
    public function addUserGroup(UserGroup $userGroups)
    {
        $this->userGroups[] = $userGroups;

        return $this;
    }

    /**
     * Remove userGroups
     *
     * @param UserGroup $userGroups
     */
    public function removeUserGroup(UserGroup $userGroups)
    {
        $this->userGroups->removeElement($userGroups);
    }

    /**
     * This shouldn't be needed as it's another object we can handle outside of here
     *
     * @param Group $group
     */
    /*public function setPrimaryGroup(Group $group)
    {
        /** @var UserGroup $primaryUserGroup *//*
        $primaryUserGroup = $this->getUserGroups()->first();
        $primaryUserGroup->setGroup($group);
    }*/

    /**
     * @return string of all user group names
     */
    public function getAllUserGroupsNames()
    {
        $groupnames = [];
        /** @var UserGroup $usergroup */
        foreach ($this->getUserGroups() as $usergroup) {
            $groupnames[] = $usergroup->getGroup()->getName();
        }

        return implode(',', $groupnames);
    }

    /**
     * Get userGroups
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUserGroups()
    {
        return $this->userGroups;
    }

    /**
     * Get primary group name
     *
     * @return string
     */
    public function getPrimaryGroupName()
    {
        /** @var UserGroup $primaryGroup */
        $primaryGroup = $this->getUserGroups()->first();

        return $primaryGroup->getGroup()->getName();
    }

    /**
     * @return Group|null
     */
    public function getPrimaryGroup()
    {
        $primaryUserGroup = $this->getPrimaryUserGroup();

        return $primaryUserGroup ? $primaryUserGroup->getGroup() : null;
    }

    /**
     * @return UserGroup|null
     */
    public function getPrimaryUserGroup()
    {
        return $this->getUserGroups()->first() ?? null;
    }

    /**
     * Add radiusAccounting
     *
     * @param Radacct $radiusAccounting
     *
     * @return User
     */
    public function addRadiusAccounting(Radacct $radiusAccounting)
    {
        $this->radiusAccounting[] = $radiusAccounting;

        return $this;
    }

    /**
     * Remove radiusAccounting
     *
     * @param Radacct $radiusAccounting
     */
    public function removeRadiusAccounting(Radacct $radiusAccounting)
    {
        $this->radiusAccounting->removeElement($radiusAccounting);
    }

    /**
     * @Groups({"user_get_2"})
     *

files/usr/share/grase/symfony4/templates/advancedSettings.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}Advanced Settings{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block javascripts_inline %}
<script>
    function render_link(data, type, row, meta) {
        return '<a href="'+ Routing.generate("grase_settings_advanced_edit", {setting: data }) +'">'+data+'</a>';
    }

    function pageJs($) {

        $('#advancedSettings').DataTable(
            {
                //retrieve: true,
                destroy: true,
                "columnDefs": [{
                    "render": render_link,
                    "targets": 0
                }]
            }
        );
    }
</script>
{% endblock %}

{% block content %}

    <div class="col-xs-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{% trans %}Advanced Settings{% endtrans %}</h3>
            </div>
            <div class="card-body">
                {% trans %}grase.advancedSettings.warning.long{% endtrans %}
                <div class="alert-danger alert">
                    <strong>{% trans %}grase.advancedSettings.warning.caution{% endtrans %}</strong><br/>
                </div>

                <table id="advancedSettings" class="table table-bordered table-hover dataTable"
                       data-paging="true" data-page-length="10" data-searching="true"
                       data-ordering="true" data-info="true" data-autowidth="true"
                       data-ajax='{"url": "{{ path('api_settings_get_collection', {'pagination': false}) }}", "dataSrc": ""}'
                       data-columns='[ {"data": "name"}, {"data": "value"} ]'

                >
                    <thead>
                    <tr>
                        <th>{% trans %}Name{% endtrans %}</th>
                        <th>{% trans %}Value{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}

files/usr/share/grase/symfony4/templates/auditlog.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}page.auditlog.header{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    {{ block('audit_table') }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block audit_table %}
<div class="card-header">
    <h3 class="card-title">{% trans %}page.auditlog.header{% endtrans %}</h3>
</div>
<div class="card-body p-10">
    <p>{% trans %}page.auditlog.information{% endtrans %}</p>

    <table id="auditLogTable" class="table table-bordered table-hover dataTable"
           data-paging="true" data-page-length="10" data-searching="true"
           data-ordering="true" data-info="true" data-autowidth="true"
           data-order="[[ 1, &quot;desc&quot; ]]" >
        <thead>
        <tr>
            <th>{% trans %}grase.timestamp{% endtrans %}</th>
            <th>{% trans %}grase.audit.level{% endtrans %}</th>
            <th>{% trans %}grase.user{% endtrans %}</th>
            <th>{% trans %}grase.ip{% endtrans %}</th>
            <th>{% trans %}grase.audit.action{% endtrans %}</th>
            <th>{% trans %}grase.audit.context{% endtrans %}</th>
        </tr>
        </thead>
        <tbody>
        {# entry \App\Entity\AuditLog #}
        {% for entry in logEntries %}
            <tr>
                <td data-order="{{ entry.createdAt | date('U') }}">{{ entry.createdAt |localizeddate('short', 'short') }}</td>
                <td>{{ entry.levelName }}</td>
                <td>{{ entry.username }}</td>
                <td>{{ entry.extra.ip | default('') }}</td>
                <td>{{ entry.message | trans()}}</td>
                <td class="json-renderer" data-json='{{ entry.context |json_encode }}'></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

files/usr/share/grase/symfony4/templates/editAdvancedSetting.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}grase.advancedSettings.edit.title{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block content %}

    <div class="col-xs-12">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">{% trans %}grase.advancedSettings.edit.title{% endtrans %}</h3>
            </div>
            <div class="card-body">
                <div class="alert-danger alert">
                    <strong>{% trans %}grase.advancedSettings.warning.caution{% endtrans %}</strong><br/>
                    {% trans %}grase.advancedSettings.warning{% endtrans %}

                </div>
                <div class="form-row">
                    <div class="col-xs-12 col-lg-6">
                        {{ form(settingForm) }}
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

files/usr/share/grase/symfony4/templates/group_edit.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}Edit Group{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}
{{ group.name }}
{% endblock page_subtitle %}

{% block content %}

    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{% trans %}Edit Group{% endtrans %}</h3>
            </div>
            <div class="box-body">
                {{ form_start(group_form) }}
                {{ form_widget(group_form) }}
                {{ form_end(group_form) }}
            </div>

        </div>
    </div>

{% endblock %}

{% block javascripts_inline %}

{% endblock %}

files/usr/share/grase/symfony4/templates/groups.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}Groups{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block content %}

    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{% trans %}Groups{% endtrans %}</h3>
            </div>
            <div class="box-body">
                <table id="groupsTable" class="dataTable table table-bordered table-hover"
                       data-paging="true" data-page-length="10" data-searching="true"
                       data-ordering="true" data-info="true" data-autowidth="true">
                    <thead>
                    <tr>
                        <th>{% trans %}Name{% endtrans %}</th>
                        <th>{% trans %}Data Limit{% endtrans %}</th>
                        <th>{% trans %}Time Limit{% endtrans %}</th>
                        <th>{% trans %}Expiry{% endtrans %}</th>
                        <th>{% trans %}Expire After{% endtrans %}</th>
                        <th>{% trans %}Comment{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for group in groups %}
                        <tr>
                            <td><a href="{{ path('grase_users', {'group': group.name}) }}">{{ group.name }}</a> <a href="{{ path('grase_group_edit', {'id': group.id} ) }}"><i class="fas fa-edit float-right"></i></a></td>
                            <td>{{ group.maxOctets|format_bytes }}</td>
                            <td>{{ group.maxSeconds }}</td>
                            <td>{{ group.expiry }}</td>
                            <td>{{ group.expireAfter }}</td>
                            <td>{{ group.comment }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}

files/usr/share/grase/symfony4/templates/pdmenu.html.twig
{% extends '@PdMenu/Default/menuBase.html.twig' %}

{# Begin Menu #}
{% block menu_begin %}
    <ul id="{{ menu.id }}" {{ arrayToAttr(menu.childAttr, {'class': 'nav'}, options) }} data-widget="treeview" role="menu" data-accordion="false">
        {% for depth in menu.child %}
            {% set menu = depth %}
            {{ block('menu_item') }}
        {% endfor %}
    </ul>
{% endblock %}

{# Create Menu Item #}
{% block menu_item %}
    <li {{ arrayToAttr(menu.listAttr, [], options) }}>
        {# Create Link #}
        {% if menu.link %}
            <a href="{{ menu.link }}" {{ arrayToAttr(menu.linkAttr, [], options) }}>
                {% if menu.extra('label_icon') %}
                    {{ options.iconTemplate|replace({ 'itext': menu.extra('label_icon') })|raw }}
                {% endif %}
                <p {{ arrayToAttr(menu.labelAttr, [], options) }}>
                    {{ menu.extra('label_translate', true) ? menu.label|trans([], options.trans_domain)|raw : menu.label|raw }}
                </p>
                {{ menu.labelAfterHtml|raw }}
            </a>
            {{ menu.linkAfterHtml|raw }}
        {% else %}
            {% if menu.extra('label_icon') %}
                {{ options.iconTemplate|replace({ 'itext': menu.extra('label_icon') })|raw }}
            {% endif %}
            <p {{ arrayToAttr(menu.labelAttr, [], options) }}>
                    {{ menu.extra('label_translate', true) ? menu.label|trans([], options.trans_domain)|raw : menu.label|raw }}
            </p>
            {{ menu.labelAfterHtml|raw }}
            {{ menu.linkAfterHtml|raw }}
        {% endif %}

        {# Create Dropdown #}
        {% if menu.child|length %}
            <ul {{ arrayToAttr(menu.childAttr, [], options) }}>
                {% for depth in menu.child %}
                    {% set menu = depth %}
                    {{ block('menu_item') }}
                {% endfor %}
            </ul>
        {% endif %}
    </li>
{% endblock %}

files/usr/share/grase/symfony4/templates/searchResults.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}grase.searchResults.title{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block content %}
    <h2>{% trans %}grase.searchResults.title{% endtrans %}</h2>
    <div class="row">

        <div class="col-xs-12 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{% trans %}grase.searchResults.title.users{% endtrans %}</h3>
                </div>
                <div class="card-body">
                    <table id="usersTable" class="table table-bordered table-hover dataTable"
                           data-paging="true" data-page-length="10" data-searching="true"
                           data-ordering="true" data-info="true" data-autowidth="true">
                        <thead>
                        <tr>
                            <th>{% trans %}grase.table.header.username{% endtrans %}</th>
                            <th>{% trans %}Last Logout{% endtrans %}</th>
                            <th>{% trans %}Group{% endtrans %}</th>
                            <th>{% trans %}Comment{% endtrans %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.username }}<span class="float-right"><a href="{{ path('grase_user_edit', {id: user.username}) }}"><i class="fas fa-user-edit"></i></a> <a data-toggle="popover" tabindex="0" data-trigger="focus" title="{% trans %}Password{% endtrans %}" data-content="{{ user.password }}"><i class="material-icons md-18 md-dark">lock</i></a></span></td>
                                <td data-order="{{ user.lastLogout ? user.lastLogout | date('U') }}">{% if user.lastLogout %}{{ user.lastLogout |localizeddate('medium', 'short') }}{% endif %}</td>
                                <td>{{ user.allUserGroupsNames }}</td>
                                <td>{{ user.comment }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        <div class="col-xs-12 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{% trans %}grase.searchResults.title.groups{% endtrans %}</h3>
                </div>
                <div class="card-body">
                    <table id="groupsTable" class="dataTable table table-bordered table-hover"
                           data-paging="true" data-page-length="10" data-searching="true"
                           data-ordering="true" data-info="true" data-autowidth="true">
                        <thead>
                        <tr>
                            <th>{% trans %}Name{% endtrans %}</th>
                            <th>{% trans %}Comment{% endtrans %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for group in groups %}
                            <tr>
                                <td><a href="{{ path('grase_users', {'group': group.name}) }}">{{ group.name }}</a> <a href="{{ path('grase_group_edit', {'id': group.id} ) }}"><i class="fas fa-edit float-right"></i></a></td>
                                <td>{{ group.comment }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

files/usr/share/grase/symfony4/templates/user_edit.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}Edit User{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}
{{ group.name }}
{% endblock page_subtitle %}

{% block content %}

    <div class="col-xs-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{% trans %}Edit User{% endtrans %}</h3>
            </div>
            <div class="card-body">
                {{ form_start(user_form) }}

                <div class="my-custom-class-for-errors">
                    {{ form_errors(user_form) }}
                </div>

                <div class="form-row">
                    <div class="col-xs-12 col-lg-6">
                        {{ form_row(user_form.username) }}
                        <div class="form-group">
                            {{ form_label(user_form.password) }}
                            <div class="input-group">
                            {{ form_widget(user_form.password) }}
                            <span class="input-group-append">
                                <button type="button" class="btn btn-dark" id="generatePasswordButton"><i class="material-icons small">refresh</i> {% trans %}Generate{% endtrans %}</button>
                            </span>
                            </div>
                            {{  form_help(user_form.password) }}
                            {# TODO add password strength to this page #}
                        </div>


                        {{ form_row(user_form.comment) }}
                        {{ form_row(user_form.primaryGroup) }}
                    </div>
                    <div class="col-xs-12 col-lg-6">
                        {{ form_row(user_form.dataLimit) }}
                        {{ form_row(user_form.timeLimit) }}
                        {{ form_row(user_form.lockMessage) }}
                        {{ form_row(user_form.save) }}
                    </div>
                </div>

                {{ form_rest(user_form) }}
                {{ form_end(user_form) }}
            </div>

            {% if user_reset_expiry_form is defined %}
            <div class="card-body">
                {{ form_start(user_reset_expiry_form) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(user_reset_expiry_form) }}
                </div>

                <div class="form-row">
                    <div class="col-xs-12 col-lg-6">
                        <div class="form-group">
                            <label >{% trans %}grase.form.user.expireAfter.label{% endtrans %}</label>
                            <input class="form-control" disabled="disabled"
                                   value="{% if user.expireAfter %}{{ user.expireAfter }}{% else %}{% trans %}grase.form.user.expireAfter.none{% endtrans %}{% endif %}">
                        </div>
                        {{ form_row(user_reset_expiry_form.expiry) }}
                        {{ form_rest(user_reset_expiry_form) }}
                        {{ form_end(user_reset_expiry_form) }}
                    </div>

                    <div class="col-xs-12 col-lg-6">
                        <h2 >{% trans %}grase.form.user.delete.label{% endtrans %}</h2>
                        <p>{% trans %}grase.form.user.delete.warning{% endtrans %}</p>
                        {{ form(user_delete_form) }}
                    </div>
                </div>

            </div>
            {% endif %}

        </div>
    </div>

{% endblock %}

{% block javascripts_inline %}
    <script>
        function pageJs($) {
            // Ensure that when a user types customs values we clear the dropdowns
            $('#user_dataLimit_dataLimitCustom').change(function () {
                if ($('#user_dataLimit_dataLimitCustom').val() != '') {
                    $('#user_dataLimit_dataLimitDropdown').val('');
                }
            });
            $('#user_timeLimit_timeLimitCustom').change(function () {
                if ($('#user_timeLimit_timeLimitCustom').val() != '') {
                    $('#user_timeLimit_timeLimitDropdown').val('');
                }
            });

            // Allow the user to auto generate a new password for the account
            $('#generatePasswordButton').click(function () {
                $.ajax(Routing.generate('grase_api_generate_password', null, true))
                    .done(function(data) {
                        $('#user_password').val(data);
                    });

            });

            // Ensure we confirm before deleting the user
            $('#user_delete_delete').click(function () {
                return confirm('{% trans with {'%username%': user.username} %}grase.form.user.submit.delete.confirm.%username%{% endtrans %}');
            })
        };
    </script>
{% endblock %}

files/usr/share/grase/symfony4/templates/users.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
    {% trans %}User Accounts{% endtrans %}
{% endblock page_title %}

{% block page_subtitle %}

{% endblock page_subtitle %}

{% block content %}

    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{% trans %}User Accounts{% endtrans %}</h3>
            </div>
            <div class="box-body">
                <table id="usersTable" class="table table-bordered table-hover dataTable"
                       data-paging="true" data-page-length="10" data-searching="true"
                       data-ordering="true" data-info="true" data-autowidth="true">
                    <thead>
                    <tr>
                        <th>{% trans %}grase.table.header.username{% endtrans %}</th>
                        <th>{% trans %}Data Usage{% endtrans %}</th>
                        <th>{% trans %}Time Usage{% endtrans %}</th>
                        <th>{% trans %}Expiry{% endtrans %}</th>
                        <th>{% trans %}Last Logout{% endtrans %}</th>
                        <th>{% trans %}Group{% endtrans %}</th>
                        <th>{% trans %}Comment{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.username }}<span class="float-right"><a href="{{ path('grase_user_edit', {id: user.username}) }}"><i class="fas fa-user-edit"></i></a> <a data-toggle="popover" tabindex="0" data-trigger="focus" title="{% trans %}Password{% endtrans %}" data-content="{{ user.password }}"><i class="material-icons md-18 md-dark">lock</i></a></span></td>
                            <td data-order="{{ user.datausagetotal }}">{{ user.datausagetotal|format_bytes }}/{{ user.datalimit|format_bytes }}</td>
                            <td data-order="{{ user.totalSessionTime }}">{{ user.totalSessionTime }}/{{ user.timelimit }}</td>
                            <td data-order="{{ user.expiry ? user.expiry | date('U') }}">{% if user.expiry %}{{ user.expiry|localizeddate('medium', 'short') }}{% endif %}{{ user.expireAfter ? "(#{user.expireAfter})" }}</td>
                            <td data-order="{{ user.lastLogout ? user.lastLogout | date('U') }}">{% if user.lastLogout %}{{ user.lastLogout |localizeddate('medium', 'short') }}{% endif %}</td>
                            <td>{{ user.allUserGroupsNames }}</td>
                            <td>{{ user.comment }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}